
#' @title Conditioned choropleth maps in loon
#'
#' @description 2-way panel of maps for visualizing multivariate data
#'
#' @param tt Tk top level window. Defaults to a new window
#' @param cc_inspector Whether to draw the custom inspector for CCmaps, which
#'   allows for variable selection, variable label update, font size adjustment
#'   and option to optimize \eqn{R^2}. Defaults to TRUE
#' @param title Title of the map. Appears in the title bar of the toplevel window.
#'   Defaults to "CCmaps"
#' @param spdf \code{SpatialPolygonsDataFrame} object to hold polygon coordinates
#'   and attributes. It should contain all variables used in analysis
#' @param respvar Name of the response value variable
#' @param respvar.lab Label for response value variable for slider. Defaults to NULL,
#'   in which case \code{respvar} is used
#' @param cond1var Name of the first conditioning variable (controls
#'   panel assignment in the vertical direction)
#' @param cond1.lab Label for first conditional variable for slider. Defaults to NULL,
#'   in which case \code{cond1} is used
#' @param cond2var Name of the second conditioning variable (controls
#'   panel assignment in the horizontal direction)
#' @param cond2.lab Label for second conditional variable for slider. Defaults to NULL,
#'   in which case \code{cond2} is used
#' @param respbreaks Determines how the response data is divided into three groups
#'   for coloring scheme. It can either be the integer 3 or a numeric vector of
#'   four break points. Defaults to 3, in which case the response values are divided
#'   into tertiles
#' @param size Font size for model value labels and\eqn{R^2}. Defaults to size 10
#' @param seg1col Color of first interval of points by \code{respvar} value.
#'   Defaults to 'blue'
#' @param seg2col Color of second interval of points by \code{respvar} value.
#'   Defaults to 'darkgrey'
#' @param seg3col Color of third interval of points by \code{respvar} value.
#'   Defaults to 'red'
#' @param optimize Logical value indicating whether panel assignment should be
#'   optimized for \eqn{R^2}. Requires a long time to compute. Defaults to FALSE,
#'   in which case the conditioning data is divided into tertiles
#' @param otry Integer (greater than 0) indicating number of values to try
#'   for optimization (see above). Required if \code{optimize = TRUE}.
#'   Defaults to 10. A higher \code{otry} value leads to more precise estimates
#'   at the cost of longer computation time
#'
#' @importFrom dplyr mutate mutate_at rowwise funs group_by ungroup summarise select
#' @importFrom magrittr %>%
#'
#' @export
#'
#' @examples
#'\dontrun{
#'
#' ### Example 1
#' ## Get data
#' library(maptools)
#' library(rgdal)
#' columbus <- readOGR(system.file("shapes/columbus.shp", package = "maptools")[1], verbose = F)
#'
#' ## Plot
#' l_ccmaps(title = "Columbus Residential Burglaries and Vehicle Thefts",
#'          spdf = columbus,
#'          respvar = "CRIME", cond1var = "PLUMB", cond2var = "HOVAL",
#'          optimize = TRUE)
#'
#'
#' ### Example 2
#' ## Get data
#' library(maptools)
#' library(rgdal)
#' nc.sids <- readOGR(system.file("shapes/sids.shp", package = "maptools")[1], verbose = F)
#'
#' proj4string(nc.sids) <- CRS("+proj=longlat +ellps=clrk66")
#' row.names(nc.sids) <- as.character(nc.sids$FIPSNO)
#'
#' nc.sids$ft.SID74 <- sqrt(1000)*(sqrt(nc.sids$SID74/nc.sids$BIR74) + sqrt((nc.sids$SID74+1)/nc.sids$BIR74))
#'
#' nc.sids$ft.NWBIR74 <- sqrt(1000)*(sqrt(nc.sids$NWBIR74/nc.sids$BIR74) + sqrt((nc.sids$NWBIR74+1)/nc.sids$BIR74))
#'
#' ## Plot
#' l_ccmaps(title = "North Carolina SIDS Rates",
#'          spdf = nc.sids,
#'          respvar = "SID79", cond1var = "BIR79", cond2var = "SID74",
#'          optimize = FALSE)
#'
#'}
#'
l_ccmaps <- function(tt = tktoplevel(), cc_inspector = TRUE,
                     title = "CCmaps", spdf,
                     respvar, respvar.lab = NULL,
                     cond1var, cond1var.lab = NULL,
                     cond2var, cond2var.lab = NULL,
                     respbreaks = 3,
                     # scale = c('unchanged', 'percent', 'log'),
                     size = 10, seg1col = 'blue', seg2col = 'darkgrey', seg3col = 'red',
                     optimize = FALSE, otry = 10) {


  # Input checks -----
  if (!is(tt, 'tkwin'))
    stop('tt should be a Tk toplevel window generated by tktoplevel()')

  if (!is.logical(cc_inspector)) {
    stop("cc_inspector must be TRUE or FALSE only")
  }

  if (!is(spdf, "SpatialPolygonsDataFrame")) {
    stop("spdf has to be of SpatialPolygonsDataFrame class")}


  if (length(unique(spdf@plotOrder)) != nrow(spdf@data)) {
    stop('plotOrder for spdf does not correspond to the number of data points')
  }


  var_len <- sapply(c('respvar', 'cond1var', 'cond2var', 'cc_inspector',
                      'optimize', 'otry', 'title', 'seg1col', 'seg2col', 'seg3col'),
                    function(x) length(get(x)))

  if (any(var_len) > 1) {
    stop(paste(paste0(names(var_len)[var_len > 1], collapse = ', '),
               "should be of length one"))
  }


  if (!is.character(respvar)) {
    stop("respvar (response variable name) should be of type character")
  }

  if (!(respvar %in% names(spdf))) {
    stop("respvar (response variable name) does not exist in the data supplied")
  }

  if (!is.null(respvar.lab) & (!is.character(respvar.lab) | length(respvar.lab) > 1)) {
    stop('Label for respvar should be a single string or NULL')
  }


  if (!is.character(cond1var)) {
    stop("cond1var (name of first conditioned variable) should be of type character")
  }

  if (!(cond1var %in% names(spdf))) {
    stop("cond1var (first conditioned variable) does not exist in the data supplied")
  }

  if (!is.null(cond1var.lab) & (!is.character(cond1var.lab) | length(cond1var.lab) > 1)) {
    stop('Label for cond1var should be a single string or NULL')
  }

  if (!is.character(cond2var)) {
    stop("cond2var (name of second conditioned variable) should be of type character")
  }

  if (!(cond2var %in% names(spdf))) {
    stop("cond2var (second conditioned variable) does not exist in the data supplied")
  }

  if (!is.null(cond1var.lab) & (!is.character(cond1var.lab) | length(cond1var.lab) > 1)) {
    stop('Label for cond2var should be a single string or NULL')
  }

  respbreaks_errmsg <- "respbreaks must be a numeric vector of four break points or the integer 3"

  if (!is.numeric(respbreaks)) {
    stop(respbreaks_errmsg)
  }

  if (length(respbreaks) == 1) {
    if (respbreaks != 3) stop(respbreaks_errmsg)
  } else if (length(respbreaks) != 4) {
    stop(respbreaks_errmsg)
  }


  if (!is.character(seg1col)) {
    stop('seg1col must be of type character')
  }

  if (!is.character(seg2col)) {
    stop('seg2col must be of type character')
  }

  if (!is.character(seg3col)) {
    stop('seg3col must be of type character')
  }


  if (!is.logical(optimize) | length(optimize) > 1) {
    stop("optimize must be TRUE or FALSE only")
  }


  if (optimize && !is.numeric(otry)) {
    stop("otry must be an integer")
  }

  if (optimize && otry %% 1 != 0) {
    stop('otry must be an integer')
  }

  if (optimize && otry < 1) {
    stop("otry must be an integer greater or equal to 1")
  }


  if (!is.character(title)) {
    stop("title must be a character string")
  }



  # Data prep -----
  n <- 9 # 9 plots from 3x3 panel

  # Group names, used for determining which regions are assigned to each plot. First number
  # refers to the horizontal conditioning variable category, and second number refers to the
  # vertical conditioning variable
  group <- c(t(outer(1:3, 1:3, FUN = 'paste0')))


  spdf@data$id <- 1:nrow(spdf@data)

  plotorder_exp <- Map(function(x) {

    n <- length(spdf@polygons[[x]]@Polygons)
    rep(x, times = n)

  }, spdf@plotOrder) %>% unlist()



  resp <- spdf@data[, respvar]
  cond1 <- spdf@data[, cond1var]
  cond2 <- spdf@data[, cond2var]

  if (!is.numeric(resp)) {
    stop("Study variable must be numeric")
  }

  if (!is.numeric(cond1) | !is.numeric(cond2)) {
    stop("Conditioning variables must be numeric")
  }


  # Setting up plots -----
  tktitle(tt) <- title


  tt$env$p_base <- vector(length = n)
  tt$env$p <- vector("list",length = n)

  for (i in 1:n) {

    tt$env$p_base[i] <- l_plot(parent = tt)

    tt$env$p[[i]] <- l_layer(tt$env$p_base[i], spdf,
                             color = "cornsilk", asSingleLayer = TRUE)

    l_scaleto_world(tt$env$p_base[i])

  }


  # Determine panel membership of polygons and colors -----

  # If break points not given, use default of equal quantiles. Otherwise, use user-defined
  # break points
  if (identical(respbreaks, 3)) {
    respcuts <- quantile(resp, probs = c(1/3, 2/3))
  } else {
    respcuts <- c(respbreaks[2], respbreaks[3])
  }

  # Categorical variable corresponding to the intervals in study variable
  spdf@data$resp_cat <- cut_interval(resp, respcuts)

  attr(spdf@data$resp_cat, 'cuts') <- respcuts
  attr(spdf@data$resp_cat, 'colors') <- assign_colors(resp, respcuts, seg1col, seg2col, seg3col)



  # If optimize=TRUE, break points for conditioning variables are obtained from the optimize()
  # function. Otherwise, use equal quantiles
  if (optimize) {

    results <- r2_optimize(otry, resp, cond1, cond2)

    cond1cuts <- c(results$cond1cut1[1], results$cond1cut2[1])
    cond2cuts <- c(results$cond2cut1[1], results$cond2cut2[1])

  } else {

    cond1cuts <- quantile(cond1, probs = c(1/3, 2/3))
    cond2cuts <- quantile(cond2, probs = c(1/3, 2/3))

  }

  # Categorical variables corresponding to the levels in conditioning variables
  # For the vertical conditioning variable, need in reverse order (plotting top to bottom, but
  # the bottom rows represent lower levels)
  spdf@data$cond1_cat <- cut_interval(-cond1, -cond1cuts)
  spdf@data$cond1_cat <- assign_levels(spdf@data$cond1_cat)

  attr(spdf@data$cond1_cat, "cuts") <- cond1cuts

  spdf@data$cond2_cat <- cut_interval(cond2, cond2cuts)
  spdf@data$cond2_cat <- assign_levels(spdf@data$cond2_cat)

  attr(spdf@data$cond2_cat, "cuts") <- cond2cuts


  data_wcol <- function(resp, resp_cat, cond1_cat, cond2_cat) {

    pal <- attr(resp_cat, 'colors')

    dat <- data.frame(id = spdf@data$id,
                      resp = resp,
                      resp_cat = resp_cat,
                      group = factor(paste0(cond1_cat, cond2_cat), levels = group))

    data_exp <- data.frame(id = dat$id[match(plotorder_exp, dat$id)],
                           resp = dat$resp[match(plotorder_exp, dat$id)],
                           resp_cat = dat$resp_cat[match(plotorder_exp, dat$id)],
                           group = as.factor(dat$group[match(plotorder_exp, dat$id)]),
                           stringsAsFactors = F) %>%
      mutate(colors = as.character(factor(resp_cat, labels = pal)))

    data_exp <- cbind(data_exp, model.matrix(~ group - 1, data_exp))

    data_exp %>% rowwise() %>%
      mutate_at(.vars = paste0('group', group),
                .funs = funs(ifelse(. == 0, 'cornsilk', colors)))

  }


  update_colors <- function(data) {

    for (k in 1:n) {

      colname <- paste0('group', group[k])

      l_configure(c(tt$env$p_base[k], tt$env$p[[k]]), color = data[[colname]])

    }
  }


  update_labels <- function(data) {

    data <- data[!duplicated(data$id), ]

    r2 <- r2_calc(data$resp, data$group)
    tcl(tt$env$r2label, 'configure', text = paste0("R^2: ", round(r2, 2)))


    model_values <- attr(r2, 'model_values')


    for (i in 1:n) {

      match <- model_values[model_values$group == group[i], ]

      if (nrow(match) == 1) {

        fitted_r <- round(match[['fitted_value']], 2)

        l_configure(c(tt$env$p_base[i], tt$env$plabel[i]), text = fitted_r)

      } else {

        l_configure(c(tt$env$p_base[i], tt$env$plabel[i]), text = "NA")

      }
    }

  }


  df <- data_wcol(resp = resp, resp_cat = spdf@data$resp_cat,
                  cond1_cat = spdf@data$cond1_cat, cond2_cat = spdf@data$cond2_cat)

  update_colors(df)


  # R2 -----
  # Model values and R^2 label
  r2 <- r2_calc(df$resp[!duplicated(df$id)], df$group[!duplicated(df$id)])
  tt$env$r2label <- tcl('label', l_subwin(tt,'r2label'), text = paste0("R^2: ", round(r2, 2)),
                        font = tkfont.create(size = size))

  model_values <- attr(r2, 'model_values')


  xcoord <- spdf@bbox[1,1] - 0.15
  ycoord <- spdf@bbox[2,1]

  tt$env$plabel <- vector(length = n)

  for (i in 1:n) {

    match <- model_values[model_values$group == group[i], ]

    if (nrow(match) == 1) {

      fitted_r <- round(match[['fitted_value']], 2)

      tt$env$plabel[i] <- l_layer_text(tt$env$p_base[i], x = xcoord, y = ycoord,
                                       text = fitted_r,
                                       size = size, index = "end", color = "grey")

    } else {

      tt$env$plabel[i] <- l_layer_text(tt$env$p_base[i], x = xcoord, y = ycoord,
                                       text = "NA",
                                       size = size, index = "end", color = "grey")

    }

    l_scaleto_world(tt$env$p_base[i])

  }


  # Update function to be used on sliders
  updateGraph <- function() {

    respcuts <- c(as.numeric(tkcget(tt$env$scaletop, "-min")),
                  as.numeric(tkcget(tt$env$scaletop, "-max")))

    cond1cuts <- c(as.numeric(tkcget(tt$env$scaleright, "-min")),
                   as.numeric(tkcget(tt$env$scaleright, "-max")))

    cond2cuts <- c(as.numeric(tkcget(tt$env$scalebottom, "-min")),
                   as.numeric(tkcget(tt$env$scalebottom, "-max")))


    resp_cat <- cut_interval(resp, respcuts)
    attr(resp_cat, 'colors') <- assign_colors(resp, respcuts, seg1col, seg2col, seg3col)


    cond1_cat <- cut_interval(-cond1, -cond1cuts)
    cond1_cat <- assign_levels(cond1_cat)

    cond2_cat <- cut_interval(cond2, cond2cuts)
    cond2_cat <- assign_levels(cond2_cat)

    new_df <- data_wcol(resp = resp, resp_cat = resp_cat,
                        cond1_cat = cond1_cat, cond2_cat = cond2_cat)

    update_colors(new_df)
    update_labels(new_df)

  }


  # Reset function to be used with the Reset button. Restores to initial slider settings when
  # the code was first ran
  Reset <- function() {

    respcuts <- attr(spdf@data$resp, 'cuts')
    cond1cuts <- attr(spdf@data$cond1_cat, 'cuts')
    cond2cuts <- attr(spdf@data$cond2_cat, 'cuts')

    tcl(tt$env$scaletop, 'configure', min = respcuts[1], max = respcuts[2])
    tcl(tt$env$scaleright, 'configure', min = cond1cuts[1], max = cond1cuts[2])
    tcl(tt$env$scalebottom, 'configure', min = cond2cuts[1], max = cond2cuts[2])


    orig_df <- data_wcol(resp = resp, resp_cat = spdf@data$resp_cat,
                         cond1_cat = spdf@data$cond1_cat, cond2_cat = spdf@data$cond2_cat)

    update_colors(orig_df)
    update_labels(orig_df)

  }


  # Sliders and labels -----
  # Creates sliders and slider labels
  tt$env$labelscaletop <- tcl('label', l_subwin(tt,'scalelabel_top'),
                              text = ifelse(is.null(respvar.lab), respvar, respvar.lab))

  tt$env$scaletop <- tcl('::minmax_scale2', l_subwin(tt, 'scaletop'),
                         from = min(resp), to = max(resp),
                         min = attr(spdf@data$resp_cat, 'cuts')[1],
                         max = attr(spdf@data$resp_cat, 'cuts')[2],
                         resolution = 0.1, orient = 'horizontal',
                         seg1col = seg1col, seg2col = seg2col, seg3col = seg3col)



  tt$env$labelscaleright <- tcl('label', l_subwin(tt,'scalelabel_right'),
                                text = ifelse(is.null(cond1var.lab), cond1var, cond1var.lab))

  tt$env$scaleright <- tcl('::minmax_scale2', l_subwin(tt, 'scaleright'),
                           from = min(cond1), to = max(cond1),
                           min = attr(spdf@data$cond1_cat, 'cuts')[1],
                           max = attr(spdf@data$cond1_cat, 'cuts')[2],
                           resolution = 0.1, orient="vertical")


  tt$env$labelscalebottom <- tcl('label', l_subwin(tt,'scalelabel_bottom'),
                                 text = ifelse(is.null(cond2var.lab), cond2var, cond2var.lab))

  tt$env$scalebottom <- tcl('::minmax_scale2', l_subwin(tt, 'scalebottom'),
                            from = min(cond2), to = max(cond2),
                            min = attr(spdf@data$cond2_cat, 'cuts')[1],
                            max = attr(spdf@data$cond2_cat, 'cuts')[2],
                            resolution = 0.1, orient = "horizontal")

  tcl(tt$env$scaletop, 'configure', command = function(...) updateGraph())
  tcl(tt$env$scalebottom, 'configure', command = function(...) updateGraph())
  tcl(tt$env$scaleright, 'configure', command = function(...) updateGraph())


  # Reset button
  tt$env$resetbutton <- tkbutton(tt, command = function(...) Reset(), text = "Reset Sliders")


  # Layout -----
  tkgrid(tt$env$labelscaletop, row = 0, column = 0, sticky = "e")
  tkgrid(tt$env$scaletop, row = 0, column = 1, sticky = "new")

  for (i in 1:3) {
    for (j in 0:2) {
      tkgrid(tt$env$p_base[(i-1)*3+j+1], row = i, column = j, sticky = "nesw")
    }
  }

  tkgrid(tt$env$labelscalebottom, row = 4, column = 0, sticky = "e")
  tkgrid(tt$env$scalebottom, row = 4, column = 1, sticky = "new")
  tkgrid(tt$env$labelscaleright, row = 1, column = 3, sticky = "sew")
  tkgrid(tt$env$scaleright, row = 2, column = 3, rowspan = 2, sticky = "new")
  tkgrid(tt$env$r2label, row = 4, column = 3, sticky="nesw")
  tkgrid(tt$env$resetbutton, row = 4, column = 0)


  tkgrid.columnconfigure(tt, 3, weight = 10, minsize = 50)
  tkgrid.rowconfigure(tt, 0, weight = 4, minsize = 50)
  tkgrid.rowconfigure(tt, 4, weight = 4, minsize = 50)

  for (i in 1:3) { tkgrid.rowconfigure(tt, i, weight = 5) }
  for (j in 0:2) { tkgrid.columnconfigure(tt, j, weight = 5) }


  # Inspector -----
  ccInspector <- function(w) {

    tt_inspector <- tktoplevel()
    tktitle(tt_inspector) <- 'CCmaps Inspector'

    overall <- tkframe(tt_inspector)
    var_selector <- tkframe(overall, relief = 'groove', borderwidth = 3)
    sz <- tkframe(overall, borderwidth = 3)
    final <- tkframe(overall, borderwidth = 3)


    # Variable section
    vars <- setdiff(names(spdf@data)[sapply(spdf@data, is.numeric)],
                    c('id', 'name', 'NAME', 'group'))


    respvar_i <- tclVar(respvar)
    box.respvarvar <- ttkcombobox(var_selector, values = vars,
                                  textvariable = respvar_i,
                                  state = 'readonly')
    respvar.lab_i <- tclVar(ifelse(is.null(respvar.lab), '', respvar.lab))
    entry.respvar.lab <- tkentry(var_selector, textvariable = respvar.lab_i, width = 30)



    cond1var_i <- tclVar(cond1var)
    box.cond1var <- ttkcombobox(var_selector, values = vars,
                                textvariable = cond1var_i,
                                state = 'readonly')
    cond1var.lab_i <- tclVar(ifelse(is.null(cond1var.lab), '', cond1var.lab))
    entry.cond1var.lab <- tkentry(var_selector, textvariable = cond1var.lab_i, width = 30)


    cond2var_i <- tclVar(cond2var)
    box.cond2var <- ttkcombobox(var_selector, values = vars,
                                textvariable = cond2var_i,
                                state = 'readonly')
    cond2var.lab_i <- tclVar(ifelse(is.null(cond2var.lab), '', cond2var.lab))
    entry.cond2var.lab <- tkentry(var_selector, textvariable = cond2var.lab_i, width = 30)



    tkgrid(tklabel(var_selector, text = 'Variable: ', anchor = 'w'),
           tklabel(var_selector, text = 'Name: ', anchor = 'w'),
           tklabel(var_selector, text = 'Label: ', anchor = 'w'),
           sticky = 'w', padx = 5, pady = 5, row = 0)


    tkgrid(tklabel(var_selector, text = 'Response: ', anchor = 'w'),
           box.respvarvar,
           entry.respvar.lab,
           sticky = 'w', padx = 5, pady = 5, row = 1)

    tkgrid(tklabel(var_selector, text = 'Conditioning 1 (vertical): ', anchor = 'w'),
           box.cond1var,
           entry.cond1var.lab,
           sticky = 'w', padx = 5, pady = 5, row = 2)


    tkgrid(tklabel(var_selector, text = 'Conditioning 2 (horizontal): ', anchor = 'w'),
           box.cond2var,
           entry.cond2var.lab,
           sticky = 'w', padx = 5, pady = 5, row = 3)


    # Font size
    currSize <- tclVar(as.character(size))
    size_disp <- tklabel(sz, textvariable = currSize)

    minus <- tkbutton(sz, text = '-', command = function() downsize())
    plus <- tkbutton(sz, text = '+', command = function() upsize())


    tkgrid(tklabel(sz, text = 'Fontsize: ', anchor = 'w'),
           minus, plus, size_disp)


    # Submit button
    opt <- tkcheckbutton(final)
    optValue <- tclVar(as.character(as.numeric(optimize)))
    tkconfigure(opt, variable = optValue)


    submit <- tkbutton(final, text = 'Submit', command = function() updatecc())


    tkgrid(tklabel(final, text = 'Optimize R^2 '), opt, submit,
           sticky = 'nse', padx = 5, pady = 5)


    tkgrid(var_selector, sticky = 'w')
    tkgrid(sz, sticky = 'w')
    tkgrid(final, sticky = 'e')
    tkgrid(overall)



    upsize <- function() {

      newsize <- as.numeric(tclvalue(currSize)) + 1
      tclvalue(currSize) <- as.character(newsize)

      tcl(tt$env$r2label, 'configure', font = tkfont.create(size = newsize))
      lapply(1:length(tt$env$plabel), function(i) l_configure(c(tt$env$p_base[i], tt$env$plabel[i]), size = newsize))

    }


    downsize <- function() {

      s <- as.numeric(tclvalue(currSize))

      if (s == 1) {
        newsize <- 1
      } else {
        newsize <- s - 1
      }

      tclvalue(currSize) <- as.character(newsize)


      tcl(tt$env$r2label, 'configure', font = tkfont.create(size = newsize))
      lapply(1:length(tt$env$plabel), function(i) l_configure(c(tt$env$p_base[i], tt$env$plabel[i]), size = newsize))

    }


    updatecc <- function() {

      # Disable any clicks until the code finishes running
      # (since optimization takes a long time to run)
      tcl(submit, 'configure', state = 'disabled')
      tcl('tk', 'busy', tt_inspector)

      if (tclvalue(respvar_i) == respvar) {

        respvar_new <- respvar

        respbreaks_new <- c(min(resp),
                            as.numeric(tkcget(tt$env$scaletop, "-min")),
                            as.numeric(tkcget(tt$env$scaletop, "-max")),
                            max(resp))

      } else {

        respvar_new <- tclvalue(respvar_i)
        respbreaks_new <- 3

      }


      if (identical(tclvalue(respvar.lab_i), '')) {
        respvar.lab_new <- NULL
      } else {
        respvar.lab_new <- respvar.lab
      }


      cond1var_new <- tclvalue(cond1var_i)

      if (identical(tclvalue(cond1var.lab_i), '')) {
        cond1var.lab_new <- NULL
      } else {
        cond1var.lab_new <- tclvalue(cond1var.lab_i)
      }

      cond2var_new <- tclvalue(cond2var_i)

      if (identical(tclvalue(cond2var.lab_i), '')) {
        cond2var.lab_new <- NULL
      } else {
        cond2var.lab_new <- tclvalue(cond2var.lab_i)
      }


      optimize_new <- as.character(tclvalue(optValue))
      optimize_new <- ifelse(optimize_new == '1', TRUE, FALSE)

      size_new <- as.numeric(tclvalue(currSize))


      l_ccmaps(tt = w, cc_inspector = FALSE,
               spdf = spdf,
               respvar = respvar_new, respvar.lab = respvar.lab_new,
               cond1var = cond1var_new, cond1var.lab = cond1var.lab_new,
               cond2var = cond2var_new, cond2var.lab = cond2var.lab_new,
               respbreaks = respbreaks_new,
               size = size_new, seg1col = seg1col, seg2col = seg2col, seg3col = seg3col,
               optimize = optimize_new, otry = otry,
               title = title)


      tcl('tk', 'busy', 'forget', tt_inspector)
      tcl(submit, 'configure', state = 'normal')

    }

    tt_inspector

  }

  if (cc_inspector) ccInspector(tt)


  ret <- list(top = tt,
              maps = list(base = tt$env$p_base, polygons = tt$env$p))

  return(invisible(ret))

}


## Helper Functions -----

# Partitions x (numeric vector) into up to intervals, with break points
# defined by cuts. Break points need not be unique
cut_interval <- function(x, cuts) {

  cut(x,
      breaks = unique(c(min(x), cuts, max(x))),
      include.lowest = TRUE)

}


# Renames the levels of a vector of factors levels to numbers
assign_levels <- function(x) {

  if (is.factor(x)) x <- droplevels(x)

  factor(x, labels = 1:nlevels(x))

}


# Determines the colors to use for polygons on maps. Needed since there might
# not be three categories for the study variable (e.g. when the first and
# second break point are equal)
assign_colors <- function(var, cuts, seg1col, seg2col, seg3col) {

  min <- min(var)
  max <- max(var)
  cut1 <- cuts[1]
  cut2 <- cuts[2]

  if (length(unique(c(min, max, cut1, cut2))) == 4) {

    c(seg1col, seg2col, seg3col)

  } else if (length(unique(c(min, max, cut1, cut2))) == 3) {

    if (min == cut1) c(seg2col, seg3col)
    else if (max == cut2) c(seg1col, seg2col)
    else if (cut1 == cut2) c(seg1col, seg3col)

  } else {

    seg2col

  }

}


#' Calculates R^2 given the study variable values and the panel assignment
#'   based on the conditioning variables
#'
#' @importFrom dplyr group_by mutate ungroup summarise select
#' @importFrom magrittr %>%
#'
r2_calc <- function(x, group) {

  overall_mean <- mean(x)

  df <- data.frame(act_value = x, group = group) %>%
    group_by(group) %>%
    mutate(fitted_value = mean(act_value)) %>%
    ungroup()


  r2 <- df %>%
    summarise(sum((fitted_value - overall_mean)^2)/sum((act_value - overall_mean)^2)) %>%
    as.numeric()

  attr(r2, 'model_values') <- df %>% select(-act_value) %>% unique()

  r2

}


# Computes the R^2 measures by trying a number of possible partitioning points
# on the two conditioning variables, and returns the results in a data.frame
# sorted in decreasing order by R^2
r2_optimize <- function(otry, resp, cond1, cond2) {

  # otry number of values to try for each conditioning variable. Picks {otry choose 2} pairs (since
  # order doesn't matter) of points as the middle two break points for partioning, as well as
  # cases where the two middle break points are equal
  cond1_seq <- seq(min(cond1), max(cond1), length.out = otry)

  cond1_combn <- cbind(combn(cond1_seq, m = 2),
                       matrix(rep(cond1_seq, times = 2), nrow = 2, byrow = T))

  cond1_combn_str <- apply(cond1_combn, 2, function(x) paste0(x, collapse = ', '))


  cond2_seq <- seq(min(cond2), max(cond2), length.out = otry)

  cond2_combn <- cbind(combn(cond2_seq, 2),
                       matrix(rep(cond2_seq, times = 2), nrow = 2, byrow = T))

  cond2_combn_str <- apply(cond2_combn, 2, function(x) paste0(x, collapse = ', '))


  r2_df <- expand.grid(cond1_combn_str, cond2_combn_str, stringsAsFactors = F) %>%
    rowwise() %>%
    transmute(cond1cut1 = unlist(strsplit(Var1, ', '))[1],
              cond1cut2 = unlist(strsplit(Var1, ', '))[2],
              cond2cut1 = unlist(strsplit(Var2, ', '))[1],
              cond2cut2 = unlist(strsplit(Var2, ', '))[2]) %>%
    mutate_all(as.numeric)

  r2s <- Map(function(resp, cond1, cond2, cond1cut1, cond1cut2, cond2cut1, cond2cut2) {

    cond1_cat <- cut_interval(-cond1, -c(cond1cut1, cond1cut2))
    cond1_cat <- assign_levels(cond1_cat)

    cond2_cat <- cut_interval(cond2, c(cond2cut1, cond2cut2))
    cond2_cat <- assign_levels(cond2_cat)


    gr <- paste0(cond1_cat, cond2_cat)

    r2_calc(resp, gr)

  }, list(resp), list(cond1), list(cond2),
  r2_df$cond1cut1, r2_df$cond1cut2, r2_df$cond2cut1, r2_df$cond2cut2)

  r2_df$r2 <- unlist(r2s)

  r2_df %>%
    arrange(desc(r2)) %>%
    data.frame()

}


# # Change scale from actual numbers to percent or log scale
# convert_act2scale <- function(scale = c('unchanged', 'percent', 'log'), val1, val2, vals = NULL) {
#
#   if (scale == 'unchanged') {
#
#     c(val1, val2) %>% pretty_scale()
#
#   } else if (scale == 'percent') {
#
#     c((val1 - min(vals))/(max(vals) - min(vals)),
#       (val2 - min(vals))/(max(vals) - min(vals))) %>% pretty_scale()
#
#   } else {
#
#     if (any(vals <= 0)) stop('Cannot use log scale for variables containing zero or negative values')
#
#     log(c(val1, val2)) %>% pretty_scale()
#
#   }
#
# }
#
#
# convert_scale2act <- function(scale = c('unchanged', 'percent', 'log'), s1, s2, vals = NULL) {
#
#   if (scale == 'unchanged') {
#
#     c(s1, s2) %>% pretty_scale()
#
#   } else if (scale == 'percent') {
#
#     min(vals) + c(pct1, pct2) * diff(range(vals)) %>% pretty_scale()
#
#   } else {
#
#     10^(c(s1, s2)) %>% pretty_scale()
#
#   }
#
# }


# Round values to 1 decimal place and pervent scientific notation
pretty_scale <- function(val) {
  round(val, 1) %>%
    format(scientific = F) %>%
    as.numeric()
}

